@startuml

start

:Pin Nova RPC;

:Controller cluster shutdown;

:Controller package updates\n(reboot if needed);

:Start DBs, DB schema update;

:Start remaining cluster services;

:Package update on computes;

while (Some computes need reboot?) is (yes)

    :Remove N from scheduler,\nlive-migrate VMs away;

    :Reboot;

    :Add back to scheduler;

endwhile (no)

:Unpin Nova RPC;

stop

@enduml
